sudo: false
language: node_js
node_js: 'lts/*'

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # package-lock.json was introduced in npm@5
  - npm install -g npm@5 # skip this if you are using node 9
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: npm run cover -- --verbose --timeout 120s
after_script: greenkeeper-lockfile-upload

after_success:
  - nyc report --reporter=text-lcov | coveralls

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  apt:
    packages:
      - google-chrome-stable
